
- name: Provision EC2 via role
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2_instance_provision
    #- ec2_instace_checks

- name: Connect and gather remote facts
  hosts: launched
  gather_facts: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ansible_test_key.pem

  roles:
    - ec2_instace_checks