#SPDX-License-Identifier: MIT-0
---
# handlers file for gunicorn
- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: Restart gunicorn
  ansible.builtin.systemd:
    name: gunicorn
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
  changed_when: true